### ISSUE TITLE
Video con sottotitoli non funzionante

### ISSUE THREAD

**Issue by dpirola** [nightflyer73/plugin.video.raitv#28]
Ho trovato un video nella sezione Replay e anche nella sezione Demand che non si avvia. L'errore che ottengo è questo:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: /dl/video/stl/Montalbano_2_.srt
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 447, in <module>
                                                play(url, pathId)
                                              File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 127, in play
                                                srtFile = raiplay.fixSRT(srtUrl)
                                              File "/storage/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 95, in fixSRT
                                                data = urllib2.urlopen(url)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 421, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
                                            ValueError: unknown url type: /dl/video/stl/Montalbano_2_.srt
                                            -->End of Python script error report<--
Altri video della stessa sezione invece funzionano correttamente.

Grazie,

Dario

**Comment by nightflyer73** [comment]
Dovresti dire anche quale versione di Kodi usi, qual è questo video e postare da qualche parte il log completo.

**Comment by dpirola** [comment]
Sto usando Kodi 17.6 con Libreelec 8.2.3 su Wetek Hub. Il video che non funziona è l'episodio "Amore" del Commissario Montalbano (https://www.raiplay.it/video/2018/02/Il-Commissario-Montalbano-2018-Amore-5e912c66-6ad2-4ab7-8732-11708ef3fb0f.html) che si può trovare nella sezione Replay e anche nella sezione Demand.
Ti allego il log file (spero di aver seguito la procedura corretta)

https://pastebin.com/Yna30v3Y

Grazie
