### ISSUE TITLE
http error 403 on plugin initialization

### ISSUE THREAD

**Issue by dasums** [nightflyer73/plugin.video.raitv#35]
Ciao nightflyer,

on initialition of the plugin a HTTP error 403 is raised. The problem seems to be the same as in the closed issue #26 . I will attach the log below. 

I am new to Kodi and Python in general, but i tried to compare my local addon source code files to the Github version. It seems to me that there is a difference between the Github and the Kodi respository. 
As the issue #26 was closed I assusmed that the fix was pushed to the Kodi repository. 

Am I right with my assumption?

In case yes, should I just replace my local files with the versions from Github?

Thanks in advance for your help.

23:12:14.783 T:1480   ERROR: XFILE::CDirectory::GetDirectory - Error getting
23:12:18.201 T:5504   ERROR: Previous line repeats 6 times.
23:12:18.201 T:5504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\Thom\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 429, in <module>
                                                log_country()
                                              File "C:\Users\Thom\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 354, in log_country
                                                country = raiplay.getCountry()
                                              File "C:\Users\Thom\AppData\Roaming\Kodi\addons\plugin.video.raitv\resources\lib\raiplay.py", line 16, in getCountry
                                                response = urllib2.urlopen(self.localizeUrl).read()
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
23:12:18.269 T:5092   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.raitv/?content_type=video
23:12:18.295 T:5092   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?content_type=video) failed

**Comment by nightflyer73** [comment]
> I am new to Kodi and Python in general, but i tried to compare my local addon source code files to the Github version. It seems to me that there is a difference between the Github and the Kodi respository.
> As the issue #26 was closed I assusmed that the fix was pushed to the Kodi repository.
> 
> Am I right with my assumption?

No :-)

Closing an issue on github means it has been fixed in this repository.

I still have to push changes to the official Kodi repository because I still have some items on my to-do list.

If you wish you can use the github version in the meantime.

**Comment by dasums** [comment]
Thanks for the feedback.

**Comment by HeinrichGit** [comment]
Wont install manually...
