### ISSUE TITLE
Il plugin ha smesso di funzionare

### ISSUE THREAD

**Issue by bad-interpreter** [nightflyer73/plugin.video.raitv#37]
Come da titolo, purtroppo il plugin ha smesso di funzionare, probabilmente a causa di qualche cambiamento lato server (errore http 403).

```
11:11:13.137 T:140079121213184   ERROR: GetDirectory - Error getting
11:11:14.255 T:140078247405312   ERROR: Previous line repeats 6 times.
11:11:14.255 T:140078247405312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/lord/.kodi/addons/plugin.video.raitv/default.py", line 429, in <module>
                                                log_country()
                                              File "/home/lord/.kodi/addons/plugin.video.raitv/default.py", line 354, in log_country
                                                country = raiplay.getCountry()
                                              File "/home/lord/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 16, in getCountry
                                                response = urllib2.urlopen(self.localizeUrl).read()
                                              File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib64/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib64/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
11:11:14.317 T:140079584046208   ERROR: GetDirectory - Error getting plugin://plugin.video.raitv/?content_type=video
11:11:14.318 T:140079584046208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?content_type=video) failed
```

**Comment by nightflyer73** [comment]
Hai provato l'ultima versione disponibile in questo repository? Io non riscontro problemi. Servono maggiori dettagli su come riprodurre l'errore.

**Comment by bad-interpreter** [comment]
Avevo installato la versione fornita direttamente dalla repo di kodi (ver 2.0.0).
Ho appena provato l'ultima versione ma mi dà comunque lo stesso errore:

```
﻿11:25:54.660 T:140542388669568  NOTICE: special://profile/ is mapped to: special://masterprofile/
11:25:54.660 T:140542388669568  NOTICE: -----------------------------------------------------------------------
11:25:54.660 T:140542388669568  NOTICE: Starting Kodi (17.6). Platform: Linux x86 64-bit
11:25:54.660 T:140542388669568  NOTICE: Using Release Kodi x64 build
11:25:54.660 T:140542388669568  NOTICE: Kodi compiled May 15 2018 by GCC 7.3.0 for Linux x86 64-bit version 4.14.40 (265768)
11:25:54.660 T:140542388669568  NOTICE: Running on Slackware 14.2 x86_64 (post 14.2 -current), kernel: Linux x86 64-bit version 4.14.41-zion
11:25:54.661 T:140542388669568  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
11:25:54.661 T:140542388669568  NOTICE: Host CPU: Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz, 4 cores available
11:25:54.661 T:140542388669568  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
11:25:54.661 T:140542388669568  NOTICE: special://xbmcbin/ is mapped to: /usr/lib64/kodi
11:25:54.661 T:140542388669568  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib64/kodi/addons
11:25:54.661 T:140542388669568  NOTICE: special://masterprofile/ is mapped to: /home/lord/.kodi/userdata
11:25:54.661 T:140542388669568  NOTICE: special://envhome/ is mapped to: /home/lord
11:25:54.661 T:140542388669568  NOTICE: special://home/ is mapped to: /home/lord/.kodi
11:25:54.661 T:140542388669568  NOTICE: special://temp/ is mapped to: /home/lord/.kodi/temp
11:25:54.661 T:140542388669568  NOTICE: special://logpath/ is mapped to: /home/lord/.kodi/temp
11:25:54.661 T:140542388669568  NOTICE: The executable running is: /usr/lib64/kodi/kodi.bin
11:25:54.661 T:140542388669568  NOTICE: Local hostname: zion.inet
11:25:54.661 T:140542388669568  NOTICE: Log File is located: /home/lord/.kodi/temp//kodi.log
11:25:54.661 T:140542388669568  NOTICE: -----------------------------------------------------------------------
11:25:54.708 T:140542388669568  NOTICE: load settings...
11:25:54.737 T:140542388669568  NOTICE: Found 1 Lists of Devices
11:25:54.737 T:140542388669568  NOTICE: Enumerated PULSE devices:
11:25:54.737 T:140542388669568  NOTICE:     Device 1
11:25:54.737 T:140542388669568  NOTICE:         m_deviceName      : Default
11:25:54.737 T:140542388669568  NOTICE:         m_displayName     : Default
11:25:54.737 T:140542388669568  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
11:25:54.737 T:140542388669568  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:25:54.737 T:140542388669568  NOTICE:         m_channels        : FL,FR
11:25:54.737 T:140542388669568  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
11:25:54.737 T:140542388669568  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
11:25:54.737 T:140542388669568  NOTICE:         m_streamTypes     : No passthrough capabilities
11:25:54.737 T:140542388669568  NOTICE:     Device 2
11:25:54.737 T:140542388669568  NOTICE:         m_deviceName      : alsa_output.pci-0000_00_1b.0.analog-stereo
11:25:54.737 T:140542388669568  NOTICE:         m_displayName     : Audio interno Stereo analogico
11:25:54.737 T:140542388669568  NOTICE:         m_displayNameExtra: Cuffie analogiche (PULSEAUDIO)
11:25:54.737 T:140542388669568  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:25:54.737 T:140542388669568  NOTICE:         m_channels        : FL,FR
11:25:54.737 T:140542388669568  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
11:25:54.737 T:140542388669568  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
11:25:54.737 T:140542388669568  NOTICE:         m_streamTypes     : No passthrough capabilities
11:25:54.740 T:140542388669568  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
11:25:54.740 T:140542388669568  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
11:25:54.740 T:140542388669568  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <network>
                                                <autodetectpingtime>30</autodetectpingtime>
                                                <curlclienttimeout>60</curlclienttimeout>
                                                <curllowspeedtime>60</curllowspeedtime>
                                                <curlretries>2</curlretries>
                                                <disableipv6>true</disableipv6>
                                              </network>
                                              <cache>
                                                <buffermode>1</buffermode>
                                                <memorysize>20971520</memorysize>
                                                <readfactor>10</readfactor>
                                              </cache>
                                              <gui>
                                                <algorithmdirtyregions>0</algorithmdirtyregions>
                                                <nofliptimeout>0</nofliptimeout>
                                              </gui>
                                              <playlistasfolders1>false</playlistasfolders1>
                                              <audio>
                                                <defaultplayer>dvdplayer</defaultplayer>
                                              </audio>
                                              <imageres>540</imageres>
                                              <fanartres>720</fanartres>
                                              <splash>false</splash>
                                              <handlemounting>0</handlemounting>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
11:25:54.740 T:140542388669568  NOTICE: Default Video Player: VideoPlayer
11:25:54.740 T:140542388669568  NOTICE: Default Audio Player: dvdplayer
11:25:54.740 T:140542388669568  NOTICE: Disabled debug logging due to GUI setting. Level 0.
11:25:54.740 T:140542388669568  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
11:25:54.740 T:140542388669568  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
11:25:54.741 T:140542388669568  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
11:25:54.741 T:140542388669568  NOTICE: Loaded playercorefactory configuration
11:25:54.741 T:140542388669568  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
11:25:54.741 T:140542388669568  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
11:25:54.759 T:140542388669568  NOTICE: Running database version Addons27
11:25:54.863 T:140542388669568  NOTICE: ADDONS: Using repository repository.xbmc.org
11:25:54.863 T:140542388669568  NOTICE: ADDONS: Using repository repository.stefanorepository
11:25:54.898 T:140541904570112  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
11:25:55.063 T:140542388669568  NOTICE: Checking resolution 16
11:25:55.258 T:140542388669568   ERROR: failed to get egl display
11:25:55.288 T:140542388669568  NOTICE: Using visual 0x28
11:25:55.351 T:140542388669568  NOTICE: GL_VENDOR = NVIDIA Corporation
11:25:55.351 T:140542388669568  NOTICE: GL_RENDERER = GeForce GTX 750 Ti/PCIe/SSE2
11:25:55.351 T:140542388669568  NOTICE: GL_VERSION = 4.6.0 NVIDIA 396.24
11:25:55.351 T:140542388669568  NOTICE: GL_SHADING_LANGUAGE_VERSION = 4.60 NVIDIA
11:25:55.351 T:140542388669568  NOTICE: GL_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX = 2097152
11:25:55.351 T:140542388669568  NOTICE: GL_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX = 2097152
11:25:55.351 T:140542388669568  NOTICE: GL_EXTENSIONS = GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_x11_sync_object GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vdpau_interop GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
11:25:55.434 T:140541925836544  NOTICE: Running database version Addons27
11:25:55.435 T:140541925836544  NOTICE: Running database version ViewModes6
11:25:55.436 T:140541925836544  NOTICE: Running database version Textures13
11:25:55.438 T:140541925836544  NOTICE: Running database version MyMusic60
11:25:55.443 T:140541925836544  NOTICE: Running database version MyVideos107
11:25:55.443 T:140541925836544  NOTICE: Running database version TV29
11:25:55.444 T:140541925836544  NOTICE: Running database version Epg11
11:25:55.445 T:140542388669568  NOTICE: start dvd mediatype detection
11:25:55.561 T:140542388669568 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
11:25:55.636 T:140542388669568  NOTICE: initialize done
11:25:55.636 T:140542388669568  NOTICE: Running the application...
11:25:55.663 T:140542388669568  NOTICE: starting zeroconf publishing
11:25:55.663 T:140542388669568  NOTICE: starting upnp client
11:25:55.665 T:140540406372096  NOTICE: ES: Starting UDP Event server on port 9777
11:25:55.665 T:140540406372096  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
11:26:15.323 T:140540889204480   ERROR: GetDirectory - Error getting
11:26:16.244 T:140540917749504   ERROR: Previous line repeats 6 times.
11:26:16.244 T:140540917749504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/lord/.kodi/addons/plugin.video.raitv.bak/default.py", line 429, in <module>
                                                log_country()
                                              File "/home/lord/.kodi/addons/plugin.video.raitv.bak/default.py", line 354, in log_country
                                                country = raiplay.getCountry()
                                              File "/home/lord/.kodi/addons/plugin.video.raitv.bak/resources/lib/raiplay.py", line 16, in getCountry
                                                response = urllib2.urlopen(self.localizeUrl).read()
                                              File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib64/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib64/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
11:26:16.276 T:140542388669568   ERROR: GetDirectory - Error getting plugin://plugin.video.raitv/?content_type=video
11:26:16.277 T:140542388669568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?content_type=video) failed
```

Dimmi pure come posso fornirti maggiori dettagli.

**Comment by nightflyer73** [comment]
Duplicato di #26.

La versione che è nel repo Kodi non funziona. Devi usare quella presente qui, almeno per il momento. Quando ho un attimo finisco la nuova release e poi la pubblico sul repo ufficiale. Purtroppo il tempo è tiranno.

**Comment by bad-interpreter** [comment]
Perfetto, ho rimosso la versione di kodi e clonato quella corrente: funziona di nuovo.
Grazie!
