### ISSUE TITLE
Errore all'apertura di programma on demand

### ISSUE THREAD

**Issue by fabiocasciano** [nightflyer73/plugin.video.raitv#39]
Gentile sviluppatore,
sto provando ad aprire un Programma On Demand e ottengo questo errore. Non so come risolvere... Grazie per il tuo lavoro.

18:48:15.844 T:1691087616  NOTICE: LoadJpeg: unable to load https://www.raiplay.it/resizegd/256x-/dl/img/2018/07/18/1531907694677_2048x1152.jpg
18:48:46.117 T:1438642944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.raitv/default.py", line 426, in <module>
                                                play(url, pathId)
                                              File "/home/osmc/.kodi/addons/plugin.video.raitv/default.py", line 119, in play
                                                url = raiplay.getVideoUrl(pathId)
                                              File "/home/osmc/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 61, in getVideoUrl
                                                response = json.load(urllib2.urlopen(url))
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
18:48:46.252 T:1925818880   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.raitv/?path_id=%2Fvideo%2F2016%2F01%2FCorreva-lanno---La-rivoluzione-sulle-ruote-LItalia-in-viaggio-negli-anni-Sessanta-del-17012016-f266f027-ac50-419c-86a8-0a86f618e53d.html%3Fjson&mode=play]

**Comment by nightflyer73** [comment]
Quando si apre un bug report, bisognerebbe sempre:

- indicare la versione di Kodi utilizzata
- indicare la versione dell'addon utilizzato
- indicare i passi per riprodurre il bug
- caricare il file di log su un servizio come pastebin.com e indicarne la URL

Diversamente è difficile capire cosa non funziona ed eventualmente cercare di aggiustarlo.

**Ricordo che l'uso di VPN, smart DNS o altro per aggirare il geo blocking non sono supportati.**

Grazie per la comprensione.

**Comment by nightflyer73** [comment]
Chiudo per mancanza di informazioni.
