### ISSUE TITLE
ERROR: GetDirectory - Error getting plugin://plugin.video.raitv/

### ISSUE THREAD

**Issue by IrpiniaPenguin** [nightflyer73/plugin.video.raitv#58]
Hi,
for a few days any attempt to access the RAI plugin has been failing.

My system info: 
- hw: raspberry pi4
- OS: Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
- Kodi version: 18.7 Leila

Here below the debug lines:
```
2021-12-26 21:44:01.176 T:2470043840   DEBUG: Previous line repeats 9 times.
2021-12-26 21:44:01.176 T:2470043840   DEBUG: StartScript - calling plugin Rai Play('plugin://plugin.video.raitv/','11','','resume:false')
2021-12-26 21:44:01.177 T:2478436544   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-12-26 21:44:01.177 T:2478436544    INFO: initializing python engine.
2021-12-26 21:44:01.177 T:2478436544   DEBUG: CPythonInvoker(14, /home/pi/.kodi/addons/plugin.video.raitv/default.py): start processing
2021-12-26 21:44:01.197 T:2478436544   DEBUG: -->Python Interpreter Initialized<--
2021-12-26 21:44:01.197 T:2478436544   DEBUG: CPythonInvoker(14, /home/pi/.kodi/addons/plugin.video.raitv/default.py): the source file to load is "/home/pi/.kodi/addons/plugin.video.raitv/default.py"
2021-12-26 21:44:01.197 T:2478436544   DEBUG: CPythonInvoker(14, /home/pi/.kodi/addons/plugin.video.raitv/default.py): setting the Python path to /home/pi/.kodi/addons/plugin.video.raitv:/home/pi/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/:/home/pi/.kodi/addons/script.module.inputstreamhelper/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/home/pi/.local/lib/python2.7/site-packages:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0
2021-12-26 21:44:01.197 T:2478436544   DEBUG: CPythonInvoker(14, /home/pi/.kodi/addons/plugin.video.raitv/default.py): entering source directory /home/pi/.kodi/addons/plugin.video.raitv
2021-12-26 21:44:01.198 T:2478436544   DEBUG: CPythonInvoker(14, /home/pi/.kodi/addons/plugin.video.raitv/default.py): instantiating addon using automatically obtained id of "plugin.video.raitv" dependent on version 2.25.0 of the xbmc.python api
2021-12-26 21:44:01.523 T:2752807104   DEBUG: CWebServer[8383]: request received for /jsonrpc
2021-12-26 21:44:01.566 T:2478436544   DEBUG: Previous line repeats 1 times.
2021-12-26 21:44:01.566 T:2478436544   DEBUG: CAddonSettings[script.common.plugin.cache]: loading setting definitions
2021-12-26 21:44:01.566 T:2478436544   DEBUG: CAddonSettings[script.common.plugin.cache]: trying to load setting definitions from old format...
2021-12-26 21:44:01.634 T:2478436544   DEBUG: CAddonSettings[script.common.plugin.cache]: loading setting definitions
2021-12-26 21:44:01.634 T:2478436544   DEBUG: CAddonSettings[script.common.plugin.cache]: trying to load setting definitions from old format...
2021-12-26 21:44:02.383 T:2478436544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.raitv/default.py", line 49, in <module>
                                                radio_stations = cache.cacheFunction(RaiPlayRadio().getChannels)
                                              File "/home/pi/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 628, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/home/pi/.kodi/addons/plugin.video.raitv/resources/lib/raiplayradio.py", line 43, in getChannels
                                                response = json.loads(utils.checkStr(urllib2.urlopen(self.channelsUrl).read()))
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                                result = self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                                return self.parent.open(new, timeout=req.timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
2021-12-26 21:44:02.383 T:2478436544   DEBUG: onExecutionDone(14, /home/pi/.kodi/addons/plugin.video.raitv/default.py)
2021-12-26 21:44:02.391 T:2973260928   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-12-26 21:44:02.457 T:2478436544    INFO: Python interpreter stopped
2021-12-26 21:44:02.457 T:2478436544   DEBUG: Thread LanguageInvoker 2478436544 terminating
2021-12-26 21:44:02.462 T:2470043840   ERROR: GetDirectory - Error getting plugin://plugin.video.raitv/
2021-12-26 21:44:03.549 T:2744414400   DEBUG: CWebServer[8383]: request received for /jsonrpc
2021-12-26 21:44:08.131 T:2973260928   DEBUG: Previous line repeats 5 times.
2021-12-26 21:44:08.131 T:2973260928   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2021-12-26 21:44:09.545 T:2470043840   DEBUG: CWebServer[8383]: request received for /jsonrpc
2021-12-26 21:44:22.755 T:2719236288   DEBUG: Previous line repeats 13 times.
2021-12-26 21:44:22.756 T:2719236288   DEBUG: Thread JobWorker 2719236288 terminating (autodelete)
2021-12-26 21:44:23.596 T:2744414400   DEBUG: CWebServer[8383]: request received for /jsonrpc
```

**Comment by IrpiniaPenguin** [comment]
In addition to what I wrote earlier, it seems that a URL referenced in RaiPlayRadio class does not work:
`channelsUrl = "http://www.raiplayradio.it/dirette/ContentSet-8e2a3414-bbfd-4a72-852b-7d827dc00e7e.html?json"`

`wget http://www.raiplayradio.it/dirette/ContentSet-8e2a3414-bbfd-4a72-852b-7d827dc00e7e.html?json
--2021-12-26 23:06:49--  http://www.raiplayradio.it/dirette/ContentSet-8e2a3414-bbfd-4a72-852b-7d827dc00e7e.html?json
Risoluzione di www.raiplayradio.it (www.raiplayradio.it)... 23.209.77.137
Connessione a www.raiplayradio.it (www.raiplayradio.it)|23.209.77.137|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta...`

**Comment by IrpiniaPenguin** [comment]
Problem solved by installing the plugin directly from zip file: https://github.com/maxbambi/plugin.video.raitv/archive/master.zip.
